# -*- coding: utf-8 -*-
"""Exception&File handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBsxDeFkNFmvw9JWDWJkqFgTEKsgPb8Y

Exceptions - Errors and unexpexted events
python will normally stop and generate error message
Types of Exception
1) syntax error - incorrect indentation , missing paranthesis
2)IndentationError - a specefic type of Syntax error that occurs when indentation of code block is not correct
3)Type error-  Occurs when a operations or function is applied to an object of inappropriate type
4)Name error- Occurs when a variable or a function name used in the code is not defined or cannot be found in current scope
5)value error- when a function recives a argument of right type but contains in appropriate value
6)Index error - occurs when trying to access the element from any list tuple or string using an indexes that is out of range
7)key error - Occurs when trying to access dictionary that does not exist in dictnory
8)AttributeError: Occurs when trying to access an attribute or a method that does not exist for a given object
9)zero division error- it occurs when you are trying to divide a no by zero

Key error
"""

dict1={'name':'priya','age':30, 'salary':1000, 'position':'intern'}

"""index error"""

lst = [20,34,45,54,22,47,65,11,23,27]
lst[12]

"""Name error"""

def my_fun():
y=10
print(y)

my_fun()
print(y)

x = 10
n = int(input('Enter the denominator: '))
div = x / n
print(f'The division of two numbers is: {div}')

"""Type error -"""

full_str = "adarsh" + 3

"""How to handle them
1)try block - use to write critical code
2) except block- if the error comes the exception block will handle error
3)else block
4)finally block

Exception Handling

try:
  # code that might raise exception
  #
except Exception1:
  # code to handle the exception1
  #..
except Exception2:
  #code to handle the exception2
  #
"""

try:
  x = 10
  n = int(input('Enter the denominator: '))
  div = x / n
  print(f'The division of two numbers is: {div}')
except ZeroDivisionError:
  print('You cannot divide a number by zero')
except ValueError:
  print('Please enter a valid number')
except:
  print('Something went wrong')

"""try:
  #critical code
  # .....
except:
  # somethingwentwrong in the try block
else:
  # nothing went wrong in your code
  #when try block runs successfully , at that time only the else block will run .. other wise it wont run
  finally:
  
"""

lst= [1,2,4]
try:
  print(lst[2])
except IndexError:
  print('Index Error: Index out of range')
else:
  print('No index error')

try:
  result = 10 / '2'
except TypeError:
  print('Type error: Unsupported operand type')
else:
  print('No type error')

"""try:
#
except Exception1:
#
else:
#
finally:
# code to execute regardless of the exception was raised or not
"""

try:
    # Fixed: added parentheses and corrected function names
    user_input = int(input('Enter your number: '))
    result = 10 / user_input
    print(f'Result: {result}')

# Fixed: Corrected "valueError" to "ValueError"
except ValueError:
    print('Invalid input. Please enter a valid number')

except ZeroDivisionError:
    print('Cannot divide by zero')

finally:
    print('This block will always run')

"""Raise keyword - is used to generate the exceptions intentionally"""

x = 10

if x > 5:
  raise ValueError('Value is too high')
else:
  print('Value is in good range')

def divide_number(a, b):
  try:
    if b == 0:
      raise ZeroDivisionError('Cannot divide by zero')
    else:
      result = a / b
      return result
  except ZeroDivisionError:
    print('Error: Division by Zero is not allowed')
    return None

print (divide_number(10,2))

print(divide_number(10,0))

"""File Handling

file.read() -> reads the entire content of the file file.txt into the variable content
"""

# Use the 'r' prefix to handle the backslashes correctly
path = r"/content/adarsh.txt"
# returns the 5 first characters of the file
with open(path, "r") as file:
    print(file.read(5))

"""Readline  method()-> readoneline from a line at the file at a time
\n > it indicates newline character
"""

file = open('/content/adarsh.txt' , 'r')
line1 = file.readline() # print the first line in my txt file
print('First line: ', line1)

"""Closing files in python is  for efficient resource management and to prevent the potential issues related to file handling"""

file = open('/content/adarsh.txt' , 'r')
file.close()

"""using try ..finally block"""

file = open('/content/adarsh.txt' , 'r')
try:
  content = file.read()
  pass
finally:
  file.close()

try:
    file = open('/content/adarsh.txt', 'r')

    try:
        content = file.read()
        print('File content: ')
        print(content)
    except IOError:
        print('Error: An IOError Occurred')
    except:
        print('Error: An unexpected error occurred')
    finally:
        file.close()

except FileNotFoundError:
    print('Error: The file does not exist or cannot be found')
except Exception:
    print('Error: An unexpected error occurred.')

"""write mode - 'w'
If the file doesnt exist it will automatically create new file if the file already exist , it indicates the file and overwrite the context
"""

# Writing to the file
with open('/content/adarsh.txt', 'w') as file:
    file.write('Hello world')

# Reading it back to verify
with open('/content/adarsh.txt', 'r') as file:
    content = file.read()
    print(content)

"""Mode-> exclusive creation mode
Open a mode for exclusive creation which means the file will be created only if it does not already exists. if the file already exists the operation fails and raises a FileExitError
"""

try:
    # We assign the opened file to the variable 'file' here
    with open('/content/adarsh2.txt', 'x') as file:
        file.write('This is a new file created using exclusive creation mode.\n')
        file.write('Writing fails if the file already exists.')
    print("File created successfully!")

except FileExistsError:
    print('File already exists. Exclusive creation (mode "x") failed.')

"""How to delete a file
To delete a file using Python , you can use os.remove() function
"""

import os
os.remove('/content/adarsh2.txt')