# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CzEHaaLzhyAZxxPAbT5jj6GCPvj_2eI

def function_name(parameters);
function_name(arguments)
"""

def greet(name):
   print('Hello, '+ name +  "!")


#call the function
greet('priya')

greet('Aman')
greet('Adarsh')

def full_name(fname , lname):
  print(fname+ " "+ lname)

#function calling
full_name(' Adarsh ' , 'bhardwaj')

"""*args -> used to take multiple arguments in one go
**kwargs -> keyword arguments
"""

def learner_details(*args):
  print('The fourth enrolled learner in my course ' + args[3])
  learner_details('Asif', 'Divyanshu','Aditya','lalit','akansha')



def learner_details(**kwargs):
    print("The fourth enrolled learner in my course:", kwargs['learner104'])

learner_details(
    learner101='Asif',
    learner102='Divyanshu',
    learner103='Aditya',
    learner104='Lalit',
    learner105='Akansha'
)

"""Default parameters"""

def user_location(country = 'India'):
    print('I am from ' + country)
   # function calling
user_location()

def eval_fun(a,c,b =10):
  return a+b-c
result = eval_fun(10,12)
print(result)

"""RETURN KEYWORD VS PRINT FUNCTION

PRINT() VS return statement
"""

def add(a,b):
  print(a+b)
#function calling
add(2,8)

def add(a,b):
  return a+b

# function calling
result = add(2,8)
print(result)

"""Write a code to check whether the given integer n is a prime no or not"""

def is_prime(n):
    if n <= 1:
        return False

    for i in range(2, n):
        if n % i == 0:
            return False

    return True


n = int(input("Enter a number: "))
result = is_prime(n)

if result:
    print(f"{n} is a prime number")
else:
    print(f"{n} is not a prime number")

"""Palindromic Numbers check code"""

def is_palindrome(n):
  str_n = str(n)
  return str_n == str_n[::-1]

n = int(input("Enter a number: "))
if is_palindrome(n):
  print(f'{n} is a palindromic number')
else:
  print(f'{n} is not a palindromic number')

"""Armstrong no :"""

def is_armstrong(n):
 s = str(n)
 num_digits = len(s)
 sum_of_cubes = sum(int(digit) ** num_digits for digit in s)
 return sum_of_cubes == n
 n = int(input('Enter your number:  '))
 if is_armstrong(n):
    print(f'{n} is an armstrong number')
 else:
    print(f'{n} is not an armstrong number')

"""Recursive functions"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Function calling
result = factorial(5)
print(result)

"""Lamda function : anoymous function"""

#ex Addition of 2 problems
add = lambda a,b : a + b
print(add(3,4))

#square of any no
square = lambda a : a**2
print(square(4))

"""Map function -"""

nums = [1,2,6,3,9]
square = lambda x:x**2
print(list(map(square,nums)))

"""reduce , filter , sort"""